version: "3.9"

services:
  # container that runs mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    networks:
      - app-network

  app:
    working_dir: /app
    # on build run Dockerfile
    build: .
    container_name: nodejs-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      # enviroment variable to store mongodb connection string
      # says where the db is located
      - MONGO_URI=mongodb://mongodb:27017/docker_mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
